// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CompleteTask(arg1:number):Promise<void>;

export function CreateCategory(arg1:string,arg2:string):Promise<number>;

export function CreateTask(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:any):Promise<number>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetTasks(arg1:number):Promise<Array<models.Task>>;

export function OpenURL(arg1:string):Promise<void>;

export function UncompleteTask(arg1:number):Promise<void>;

export function UpdateCategory(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateNextReset(arg1:number):Promise<void>;

export function UpdateTask(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:any):Promise<void>;

export function UpdateTasksOrder(arg1:Array<main.TaskOrder>):Promise<void>;
