// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTask(arg1) {
  return window['go']['main']['App']['CompleteTask'](arg1);
}

export function CreateCategory(arg1, arg2) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2);
}

export function CreateTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function UncompleteTask(arg1) {
  return window['go']['main']['App']['UncompleteTask'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3);
}

export function UpdateNextReset(arg1) {
  return window['go']['main']['App']['UpdateNextReset'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}
