// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateCategory(arg1:string,arg2:string):Promise<number>;

export function CreateTask(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:any):Promise<number>;

export function DeleteCategory(arg1:number):Promise<void>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetTasks(arg1:number):Promise<Array<models.Task>>;
